// The pure half of the font pipeline: read a css2 response, write a @font-face
// block. No network and no filesystem, so scripts/check-fonts.mjs can exercise it
// against canned Google responses — which matters, because the live API is the one
// thing the build can't rely on (vercel/next.js#99114 is exactly that).
import { URL_PREFIX, BEGIN_MARK, END_MARK, SUBSET, faceFile } from "./font-manifest.mjs";

/** Pull the @font-face blocks out of a css2 response, keeping only `subset`.
 *
 *  A css2 response is a run of `/* subset *\/ @font-face { ... }` blocks, one per
 *  (style, weight, unicode range). Google answers with either a static instance
 *  per weight (`font-weight: 700`) or, for a variable family, one file covering a
 *  range (`font-weight: 400 900`). Both shapes are handled: a range keeps its
 *  range in the output and lands in a single `-var` file the browser interpolates,
 *  which is why the face count can come back lower than the manifest asked for. */
export function parseFaces(css, subset = SUBSET) {
  const faces = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/gi;
  for (const m of css.matchAll(re)) {
    if (m[1] !== subset) continue;
    const body = m[2];
    const pick = (k) => body.match(new RegExp(k + ":\\s*([^;]+);"))?.[1]?.trim();
    const url = body.match(/url\(([^)]+)\)/)?.[1]?.replace(/['"]/g, "");
    if (!url) continue;
    const style = pick("font-style") || "normal";
    faces.push({
      family: (pick("font-family") || "").replace(/['"]/g, ""),
      italic: style.startsWith("italic") || style.startsWith("oblique"),
      weight: pick("font-weight") || "400",
      range: pick("unicode-range") || "",
      url,
    });
  }
  return faces;
}

/** One `{family, italic, weight, range}` -> the file it is stored as. */
export function fileFor(face) {
  return faceFile(face.family, face.weight, face.italic);
}

/** Collapse a family's faces so a variable font is stored and declared ONCE.
 *
 *  Asked for several discrete weights of a VARIABLE family, the css2 API answers with
 *  one @font-face per weight that all point at the SAME woff2 url. Taken literally
 *  that stores N byte-identical copies and makes a page using three weights download
 *  the file three times — the opposite of the point of self-hosting. (Verified against
 *  the real downloads: 21 of the 31 families are variable, and md5 plus fontTools'
 *  fvar tables confirmed one file serving every weight. 73 of 130 files were copies,
 *  2.49 MB of 3.73 MB.)
 *
 *  So faces that share a url are one face covering a weight RANGE. A single value
 *  renders correctly too — the wght axis is simply set to it, which is why nothing
 *  ever looked wrong — but it costs a file per weight.
 *
 *  The file keeps the LOWEST weight's name rather than a `-var` name, so this is
 *  idempotent against the files already on disk.
 *
 *  The declared range spans exactly the weights the manifest asked for, not the font's
 *  full axis, so which weight matches which face does not change. */
export function collapseVariable(faces) {
  const byUrl = new Map();
  for (const f of faces) {
    const key = `${f.italic}\u0000${f.url ?? fileFor(f)}`;
    if (!byUrl.has(key)) byUrl.set(key, []);
    byUrl.get(key).push(f);
  }
  const rows = [];
  for (const group of byUrl.values()) {
    const sorted = group.slice().sort((a, b) => Number(a.weight) - Number(b.weight));
    const lo = sorted[0], hi = sorted[sorted.length - 1];
    rows.push({
      ...lo,
      weight: sorted.length > 1 ? `${lo.weight} ${hi.weight}` : lo.weight,
      file: fileFor(lo),
      covers: sorted.length,
    });
  }
  return rows;
}

/** The generated block, markers included, ready to splice into tokens.css.
 *
 *  font-display:swap keeps text readable while a face loads — the same policy as
 *  before, but the wait is now a same-origin hit on a file cached for a year
 *  rather than two third-party round trips. */
export function renderBlock(declared) {
  const rows = declared.slice().sort((a, b) =>
    a.family.localeCompare(b.family) ||
    Number(a.italic) - Number(b.italic) ||
    String(a.weight).localeCompare(String(b.weight), undefined, { numeric: true }));
  return [
    BEGIN_MARK,
    // Byte-for-byte what fetch-fonts.ps1 writes. The two fetchers have to produce the
    // same tokens.css or whichever ran last shows up as a spurious diff — and it must
    // stay ASCII, because PowerShell 5.1 reads its own source as Windows-1252 and an
    // em dash there breaks the script outright. check-fonts.mjs enforces both.
    "/* Generated by scripts/fetch-fonts.ps1 (or .mjs) from scripts/font-manifest.json.",
    "   Do not hand-edit between the markers. Add a face to the manifest and re-run the",
    "   fetcher. These rules live in tokens.css because every standalone tool page",
    "   already loads it, so they cost no extra request at all.",
    "   A weight RANGE means a variable font: Google serves one file for every weight of",
    "   a variable family, so one face covers the span instead of one file per weight. */",
    ...rows.map((d) => [
      "@font-face {",
      `  font-family: "${d.family}";`,
      `  font-style: ${d.italic ? "italic" : "normal"};`,
      `  font-weight: ${d.weight};`,
      "  font-display: swap;",
      `  src: url("${URL_PREFIX}/${d.file ?? fileFor(d)}") format("woff2");`,
      ...(d.range ? [`  unicode-range: ${d.range};`] : []),
      "}",
    ].join("\n")),
    END_MARK,
  ].join("\n");
}

/** Replace the generated region of a tokens.css string, or insert it.
 *  Returns the new text. Throws if exactly one marker is present, which would
 *  mean someone edited the region by hand and the boundaries can't be trusted. */
export function spliceBlock(css, block) {
  const i = css.indexOf(BEGIN_MARK), j = css.indexOf(END_MARK);
  if (i >= 0 && j > i) return css.slice(0, i) + block + css.slice(j + END_MARK.length);
  if (i >= 0 || j >= 0) throw new Error("tokens.css has one generated marker but not the other");
  // First run. The faces must come before anything that sets a font-family, and
  // tokens.css already opens with the self-hosted non-Google faces, so the block
  // goes in just above the first of those.
  const anchor = css.indexOf("@font-face");
  return anchor >= 0 ? css.slice(0, anchor) + block + "\n\n" + css.slice(anchor) : block + "\n\n" + css;
}
